version: '3'

services:

  odoo:
    image: codions/odoo:12.0
    container_name: odoo
    restart: always
    volumes:
      - odoo_data:/opt/dados
      - odoo_themes:/opt/odoo/themes

    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: odoo
      PG_PASSWORD: secret
      PORT: 8069
      LONGPOLLING_PORT: 8072
      WORKERS: 3
      ODOO_PASSWORD: secret
      ODOO_VERSION: 12.0

      # ODOO_ENTERPRISE: 0
      # TRUSTCODE_ENTERPRISE: 0

      # Optional database name (required if you use autoupdate command when run the image)
      DATABASE: odoo_erp

      # CPU limit before timeout
      # TIME_CPU: 600

      # Real limit before timeout
      # TIME_REAL: 720

      # Disable odoo logs to a file, instead output to standard (useful with autoupdate)
      DISABLE_LOGFILE: 0

    ports:
      - "8080:8069"
      - "8071:8071"
      - "8072:8072"
    depends_on:
      - postgres
      - maildev

  postgres:
    container_name: postgres
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo_erp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports: 
      - "8081:8080"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: maildev
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  odoo_data:
  odoo_themes:
  postgres_data: